backend:
  name: github
  repo: xytengc/xytengc.github.io
  branch: main
  site_domain: xytengc.github.io

publish_mode: editorial_workflow
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "摘要", name: "excerpt", widget: "text", required: false }
      - { label: "内容", name: "body", widget: "markdown" }
