# Netlify CMS configuration
backend:
  name: github          # 直接走 GitHub
  repo: xytengc/xytengc.github.io
  branch: main
  site_domain: xytengc.github.io   # 必填，回调用
  base_url: https://api.netlify.com   # 固定
  auth_endpoint: auth                 # 固定
  client_id: Ov23liXGBUIHeygkv3Vu            # 刚才生成的
  client_secret: 7bd599a28d56ae36bfafd7587d554e8dd8723f00               # 刚才生成的
media_folder: "img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "博客文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "更新日期", name: "updated", widget: "datetime", required: false }
      - { label: "分类", name: "categories", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "头图", name: "header-img", widget: "image", required: false }
      - { label: "摘要", name: "excerpt", widget: "text", required: false }
      - { label: "正文", name: "body", widget: "markdown" }